# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clientes.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'clientes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lientes.proto\x12\x08\x63lientes\"\x1c\n\x0e\x43lienteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x0f\x43lienteResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2S\n\x0e\x43lienteService\x12\x41\n\nGetCliente\x12\x18.clientes.ClienteRequest\x1a\x19.clientes.ClienteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clientes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTEREQUEST']._serialized_start=28
  _globals['_CLIENTEREQUEST']._serialized_end=56
  _globals['_CLIENTERESPONSE']._serialized_start=58
  _globals['_CLIENTERESPONSE']._serialized_end=116
  _globals['_CLIENTESERVICE']._serialized_start=118
  _globals['_CLIENTESERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
